---
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: sib-cis-compliance
  namespace: openshift-compliance
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "4"
profiles:
  - name: sib-ocp4-cis
    kind: TailoredProfile
    apiGroup: compliance.openshift.io/v1alpha1
  - name: sib-ocp4-cis-node
    kind: TailoredProfile
    apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
  name: all-nodes-scan-no-remediation
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1
