apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: sib-ocp4-cis
  annotations:
    compliance.openshift.io/product-type: Platform
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  extends: ocp4-cis
  setValues: []
  description: A customized profile for SIB based on ocp4-cis-node
  title: OCP4-CIS customized profile for SIB
  enableRules: []
  disableRules: []
---
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: sib-ocp4-cis-node
  annotations:
    compliance.openshift.io/product-type: Node
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  extends: ocp4-cis-node
  description: A customized profile for SIB based on ocp4-cis-node
  setValues: []
  title: OCP4-CIS-NODE customized profile for SIB
  enableRules: []
  disableRules: []
