---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    kubernetes.io/metadata.name: etcd-backup
  name: "etcd-backup"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
