---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "etcd-backup-sa"
  namespace: "etcd-backup"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-for-etcd-backup
  namespace: "etcd-backup"
  annotations:
    argocd.argoproj.io/sync-wave: "4"
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  - anyuid
  - hostaccess
  - hostnetwork
  - hostmount-anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: privileged-for-etcd-backup-rb
  namespace: "etcd-backup"
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  - kind: ServiceAccount
    name: "etcd-backup-sa"
    namespace: "etcd-backup"
roleRef:
  kind: Role
  name: privileged-for-etcd-backup
  apiGroup: rbac.authorization.k8s.io
  namespace: "etcd-backup"
